name: Publish Docker image
env:
  DEPLOY_PACKAGE_NAME : "v:${{ github.sha }}"

#on:
#  release:
#    types: [published]

on:
  push:
    branches: [master]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
            
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |            
            ghcr.io/${{ github.repository }}

      - name: Execute few commands
        run : |        
          echo "Hello Message1"
          echo "Deploy package name: ${{ env.DEPLOY_PACKAGE_NAME }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true          
          tags: |
           ghcr.io/${{ github.repository }}:${{ env.DEPLOY_PACKAGE_NAME }}
           ghcr.io/${{ github.repository }}:latest

      #- name: Build and push Docker images
      #  uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      #  with:
      #    context: .
      #    push: true
      #    tags: ${{ steps.meta.outputs.tags }}
      #    labels: ${{ steps.meta.outputs.labels }}